docs: add cookbook snippets for attestations and verifications
KILTprotocol/docs pull request #104
Opened 2022-05-30 13:00 UTC by ntn-x2

WIP.

Fixes https://github.com/KILTprotocol/ticket/issues/2008.

2022-05-31 17:09 UTC, tjwelde commented
Since I removed all the json examples in the concept section, I would love to add them in the cookbook again. I also have an idea on how to generate them from code. Will provide an example soon.

2022-06-01 10:01 UTC, tjwelde commented
Here is a draft PR, which shows how to do it: https://github.com/KILTprotocol/docs/pull/108.
Not being able to server-side render it is a big downside in my opinion. What do you think?

2022-06-01 15:12 UTC, wischli requested changes
The content LGTM! However, there is a high number of missing new lines and lower cased CTypes. Not sure, if I caught all of them. 

Moreover, the three KILT roles (Claimer, Attester, Verifier) are sometimes capitalized and sometimes not. This should be normalized. I would be fine in doing this in a separate PR as it will probably need to touch even more files.

2022-06-01 15:12 UTC, wischli commented on docs/concepts/04_Credentials/01_overview.md
> +To get a Credential a Claimer needs to go through following process:
```suggestion
To get a Credential, a Claimer needs to go through following process:
```

2022-06-01 15:12 UTC, wischli commented on docs/concepts/04_Credentials/01_overview.md
> +1. Find a **CType**, a Claim should be based on (Can be advertised by the potential Attester and Verifier)
```suggestion
1. Find a **CType**, a Claim should be based on (can be advertised by the potential Attester and Verifier)
```

2022-06-01 15:12 UTC, wischli commented on docs/concepts/04_Credentials/01_overview.md
> +To verify the Credential a Claimer can send a presentation of it to a Verifier
```suggestion
To verify the Credential, a Claimer can send a presentation of it to a Verifier
```

2022-06-01 15:12 UTC, wischli commented on docs/concepts/04_Credentials/02_ctypes.md
> +CTypes are data types specific to KILT that define the structure of a claim (i.e. the data model for your claim). They are based on JSON Schema, a standard used to annotate and validate JSON document
New line missing
```suggestion
CTypes are data types specific to KILT that define the structure of a claim (i.e. the data model for your claim). 
They are based on JSON Schema, a standard used to annotate and validate JSON documents.
The schema defines which properties exist and what their type should be, e.g., a string, a number, an object, etc.
```

2022-06-01 15:12 UTC, wischli commented on docs/concepts/04_Credentials/02_ctypes.md
> +KILT uses [JSON-Schema](https://json-schema.org/) (currently draft-07) to validate and annotate data in a strict format. This data format for [CType models](https://github.com/KILTprotocol/sdk-js/blo
New line
```suggestion
KILT uses [JSON-Schema](https://json-schema.org/) (currently draft-07) to validate and annotate data in a strict format.
This data format for [CType models](https://github.com/KILTprotocol/sdk-js/blob/develop/packages/core/src/ctype/CTypeSchema.ts) forms a CType with the definition of its characteristics.
The following are all required properties of the schema, with no additional properties allowed:
```

2022-06-01 15:12 UTC, wischli commented on docs/concepts/04_Credentials/02_ctypes.md
> +- Properties: Each property is the attribute the claimer wishes to have attested by the attester.
Inconsistency in the capitalization after `:`
```suggestion
- Title: Defines a user-friendly name for the CType that makes it easier for users to contextualise
- Properties: Each property is the attribute the claimer wishes to have attested by the attester.
```

2022-06-01 15:12 UTC, wischli commented on docs/concepts/04_Credentials/02_ctypes.md
> +The hash of the CType is used to identify and anchor it to the chain. This `hash` is stored on-chain via the store method.
New line
```suggestion
The hash of the CType is used to identify and anchor it to the chain.
This `hash` is stored on-chain via the store method.
```

2022-06-01 15:12 UTC, wischli commented on docs/concepts/04_Credentials/02_ctypes.md
> +KILT uses the hashing algorithm blake2b, hashing the CType contents. The object is sorted by a canonicalization algorithm before hashing to ensure that semantically equivalent CTypes with different o
New line
```suggestion
KILT uses the hashing algorithm blake2b, hashing the CType contents.
The object is sorted by a canonicalization algorithm before hashing to ensure that semantically equivalent CTypes with different order of their properties would produce the same output hash.
```

2022-06-01 15:12 UTC, wischli commented on docs/concepts/04_Credentials/02_ctypes.md
> +The `$id` is generated, by prepending the hash (in hex form) with `kilt:ctype`. A typical CType id would look like this: `kilt:ctype:0xba15bf4960766b0a6ad7613aa3338edce95df6b22ed29dd72f6e72d740829b84
New line
```suggestion
The `$id` is generated, by prepending the hash (in hex form) with `kilt:ctype`.
A typical CType id would look like this: `kilt:ctype:0xba15bf4960766b0a6ad7613aa3338edce95df6b22ed29dd72f6e72d740829b84`
```

2022-06-01 15:12 UTC, wischli commented on docs/concepts/04_Credentials/02_ctypes.md
> +CTypes can be stored on the blockchain. After creating a CType, the `store` transaction will include the full CType as a remark and will anchor the hash of it on the chain. Querying is not trivial, s
New line
```suggestion
CTypes can be stored on the blockchain.
After creating a CType, the `store` transaction will include the full CType as a remark and will anchor the hash of it on the chain.
Querying is not trivial, since the transaction would have to be found in the blockchain history, but it can be retrieved from indexing services.
```

2022-06-01 15:12 UTC, wischli commented on docs/concepts/04_Credentials/02_ctypes.md
> +A Claimer can apply for a new credential by requesting a CType from the Attester. The Claimer then creates a Claim, based on the CType and sends the information to be attested to the Attester. The At
New line
```suggestion
A Claimer can apply for a new credential by requesting a CType from the Attester.
The Claimer then creates a Claim, based on the CType and sends the information to be attested to the Attester.
The Attester confirms the information and returns a credential.
```

2022-06-01 15:12 UTC, wischli commented on docs/concepts/04_Credentials/02_ctypes.md
> +A Verifier can request a credential from a Claimer that follows a given CType. For example, a gaming company may request a specific credential to verify the gamer's ranking. Depending on how this cre
New line
```suggestion
A Verifier can request a credential from a Claimer that follows a given CType.
For example, a gaming company may request a specific credential to verify the gamer's ranking.
Depending on how this credential was created initially, this can be done with the software development kit (SDK) messaging, or in other ways independent of the protocol (e.g., via browser extensions, email, QR code, etc.)
```

2022-06-01 15:12 UTC, wischli commented on docs/concepts/04_Credentials/03_claiming.md
> +As KILT is an open system, any entity can make a claim about themselves. A claim (as in the real world) can only be trusted, if another trusted entity (we call them Attesters) confirms this claim. A
New line
```suggestion
As KILT is an open system, any entity can make a claim about themselves.
A claim (as in the real world) can only be trusted if another trusted entity (we call them Attesters) confirms this claim.
A Verifier therefore trusts specific Attesters, who attest Claims from Claimers.
```

2022-06-01 15:12 UTC, wischli commented on docs/concepts/04_Credentials/03_claiming.md
> +In KILT, claims are based on claim types (CTypes). A claimer can either create a new CType or, when KILT is established and standard CTypes are available, may use an existing CType when creating thei
New line
```suggestion
In KILT, claims are based on claim types (CTypes).
A claimer can either create a new CType or, when KILT is established and standard CTypes are available, may use an existing CType when creating their claim.
```

2022-06-01 15:12 UTC, wischli commented on docs/concepts/04_Credentials/03_claiming.md
> +The resulting claim is referencing the ctype by its hash and includes the DID of the owner (i.e., the subject) of the claim.
Capitalize
```suggestion
The resulting claim is referencing the CType by its hash and includes the DID of the owner (i.e., the subject) of the claim.
```

2022-06-01 15:12 UTC, wischli commented on docs/concepts/04_Credentials/04_attestation.md
> +- creates an attestation object from the root hash of the RequestForAttestation and the attester’s address.
Above, we put `RequestForAttestation` into code formatting. IMO, we should continue in doing so then.
```suggestion
- creates an attestation object from the root hash of the `RequestForAttestation` and the attester’s address.
```

2022-06-01 15:12 UTC, wischli commented on docs/concepts/04_Credentials/05_verification.md
> +KILT allows a verifier to check if the information in a credential presented by a claimer is correct and valid. With the presentation of the credential, the claimer also presents evidence to the vali
New line
```suggestion
KILT allows a verifier to check if the information in a credential presented by a claimer is correct and valid.
With the presentation of the credential, the claimer also presents evidence to the validator that a third party (attester) ensured the correctness of the claimer’s attributes.
```

2022-06-01 15:12 UTC, wischli commented on docs/concepts/04_Credentials/05_verification.md
> +- **RequiredProperties**: Per ctype, the verifier can define which properties they would at least need to see, to fulfill the verification. More on "Selective Disclosure" later.
Capitalize
```suggestion
- **CTypes**: Here the verifier can define which CType they can work with for their use-case. They can provide multiple options, which have to be regarded as alternatives.
- **TrustedAttesters**: Per CType, the verifier can define which attesters they would automatically trust.
- **RequiredProperties**: Per CType, the verifier can define which properties they would at least need to see, to fulfill the verification. More on "Selective Disclosure" later.
```

2022-06-01 15:12 UTC, wischli commented on docs/concepts/04_Credentials/05_verification.md
> +However, this does not verify that the claimer is the rightful/legitimate owner of the credential presented. So please read on for how to check that.
NEw line
```suggestion
However, this does not verify that the claimer is the rightful/legitimate owner of the credential presented.
So please read on for how to check that.
```

2022-06-01 15:12 UTC, wischli commented on docs/concepts/04_Credentials/05_verification.md
> +A credential is linked to the did (decentralized identifier) of the claimer. This did can be used to obtain the public key of the claimer.
New line
```suggestion
A credential is linked to the did (decentralized identifier) of the claimer.
This did can be used to obtain the public key of the claimer.
```

2022-06-01 15:12 UTC, wischli commented on docs/concepts/04_Credentials/05_verification.md
> +The verifier assumes that the private key for this public key is only known to the legitimate owner of the credential. Therefore, when sending the request for the credential, the verifier challenges
New line
```suggestion
The verifier assumes that the private key for this public key is only known to the legitimate owner of the credential.
Therefore, when sending the request for the credential, the verifier challenges the claimer to sign a nonce (a random number that is used once) that the verifier sends together with his request.
```

2022-06-01 15:12 UTC, wischli commented on docs/concepts/04_Credentials/05_verification.md
> +After the verifier has checked that the credential is valid and belongs to the claimer, they still need to verify that they have received all the information they require as the credential received c
New line
```suggestion
After the verifier has checked that the credential is valid and belongs to the claimer, they still need to verify that they have received all the information they require as the credential received could contain the right values, but not the right semantics.
For example, the _age_ property could have different meanings depending on whether it was for a passport CType or a Whisky Certificate CType. Therefore, the verifier has to check if the CType matches the CType expected.
```

2022-06-01 15:12 UTC, wischli commented on docs/concepts/06_Advanced/nested-ctypes.md
> +JSON-schema provides a referencing keyword `$ref` that can be used as a pointer from other JSON schemas. This allows CTypes to either reference fields in other CTypes or nest entire CTypes within one
New line
```suggestion
JSON-schema provides a referencing keyword `$ref` that can be used as a pointer from other JSON schemas.
This allows CTypes to either reference fields in other CTypes or nest entire CTypes within one another, providing flexibility for several different use cases.
```

2022-06-01 15:12 UTC, wischli commented on docs/concepts/06_Advanced/terms-and-quote.md
> +These Terms are defined and agreed upon before the attestation is created. This part of the process requires interaction and communication between both parties. This communication can be done indepen
New line
```suggestion
These Terms are defined and agreed upon before the attestation is created.
This part of the process requires interaction and communication between both parties.
The communication can be done independently, e.g. in person, via messaging, on social media etc., or via the KILT software development kit (SDK).
```

2022-06-01 15:12 UTC, wischli commented on docs/concepts/06_Advanced/terms-and-quote.md
> +  - The partial claim has to at least contain the ctype hash the attestation will be based on.
Newline and inconsistencies in the capitalization of the Claimer, Attester and Verifier roles. Throughout the entire PR, some documents use uppercase, others lower and this document uses both. I propose to normalize and capitalize.

```suggestion
- **Claim**: A partial claim with information the attester already has about the claimer.
This helps the claimer to pre-fill their claims with information only known to the attester.
  - The partial claim has to at least contain the ctype hash the attestation will be based on.
```

2022-06-01 15:12 UTC, wischli commented on docs/concepts/06_Advanced/terms-and-quote.md
> +- **Delegation Id**: An Attester may be part of a top-down trust authority, given them the right to attest in the name of an institution, or similar. E.g. a business giving the right to their employe
New lines

```suggestion
- **Delegation Id**: An Attester may be part of a top-down trust authority, given them the right to attest in the name of an institution, or similar. 
E.g., a business giving the right to their employee to attest the claim on their behalf.
This is a delegation.
If the Attester has attestation rights, delegated from another entity, this should be stated clearly at this point.
See [here](/docs/concepts/distributed_trust) for details on how to create a delegation.
```

2022-06-01 15:12 UTC, wischli commented on docs/concepts/06_Advanced/terms-and-quote.md
> +Only the ctype hash in the partial claim is required, everything else is optional.
Capitalize
```suggestion
Only the CType hash in the partial claim is required, everything else is optional.
```

2022-06-01 15:12 UTC, wischli commented on docs/concepts/06_Advanced/terms-and-quote.md
> +A Quote consists of costs, a time frame until the attestation will be delivered and the terms and conditions of the work to be performed. It may be sent to the Claimer by the Attester as part of the
New line
```suggestion
A Quote consists of costs, a time frame until the attestation will be delivered and the terms and conditions of the work to be performed.
It may be sent to the Claimer by the Attester as part of the Terms.
In cases where multiple Attesters provide the same attestation (for example, a car inspection) the Claimer may request a Quote from several Attesters to choose the Attester with the best conditions.
```

2022-06-01 15:12 UTC, wischli commented on docs/develop/03_workshop/04_attester/03_ctype.md
> +If you want to learn more about CTypes take a look at our [in depth CType documentation](/docs/concepts/credentials/ctypes). You can also [read through existing ctypes in our ctype-index](https://git
New line
```suggestion
If you want to learn more about CTypes take a look at our [in depth CType documentation](/docs/concepts/credentials/ctypes). 
You can also [read through existing ctypes in our ctype-index](https://github.com/KILTprotocol/ctype-index).
```

2022-06-02 07:45 UTC, wischli approved these changes
LGTM!

2022-06-02 09:27 UTC, tjwelde reviewed
Short and sweet. Shall we incorporate json examples of the resulting objects separately?
I was also thinking, if we should mention the messaging system here, too. Since it is an integral part of the communication channel and provides features, e.g. to request a credential as a verifier...

2022-06-02 09:27 UTC, tjwelde commented on code_examples/core_features/claiming/01_create_ctype.ts
> +    title: `Drivers License by ${creatorDid.did}`,
Is this to add randomness for the tests?

2022-06-02 09:33 UTC, ntn-x2 commented on code_examples/core_features/claiming/01_create_ctype.ts
> +    title: `Drivers License by ${creatorDid.did}`,
Yes.

2022-06-02 09:33 UTC, ntn-x2 commented
@tjwelde I will add the links in the editorial review, as right now there are kind of circular dependencies.

2022-06-02 11:08 UTC, merged