feat: dynamic deposit
KILTprotocol/docs pull request #242
Opened 2023-04-24 08:50 UTC by Ad96el

## fixes [2636](https://github.com/KILTprotocol/ticket/issues/2636)

Documentation for the [PR](https://github.com/KILTprotocol/kilt-node/pull/507).

2023-05-11 08:38 UTC, ntn-x2 reviewed
One-line-one-sentence 😀

2023-05-11 08:38 UTC, ntn-x2 commented on docs/develop/02_chain/02_pallets/01_did.md
> +When writing a DID to the chain the submitter of the extrinsic has to pay a deposit. The base deposit are currently 2 KILT.
```suggestion
When writing a DID to the chain the submitter of the extrinsic has to pay a deposit.
The base deposit is currently 2 KILT.
```

2023-05-11 08:38 UTC, ntn-x2 commented on docs/develop/02_chain/02_pallets/01_did.md
> +For additional used storage, for example by adding more service endpoints, the deposit increases.
```suggestion
For additional used storage, for example by adding more services, more tokens are taken as deposit, depending on the amount of additional storage taken.
```

2023-05-11 08:38 UTC, ntn-x2 commented on docs/develop/02_chain/02_pallets/01_did.md
> +Releasing memory reduces the deposit. This is to incentivize deleting unused DIDs to save storage on the chain.
```suggestion
Freeing up memory reduces the deposit.
This is to incentivize deleting unused DIDs or keys to reduce the total storage of the chain.
```

2023-08-15 12:44 UTC, weichweich requested changes
minor requests

2023-08-15 12:44 UTC, weichweich commented on docs/develop/02_chain/02_pallets/01_did.md
> +The base deposit is currently 2 KILT.
This suggests that it's 2 KILT exactly. Either give an exact number or make clear that it's an approximation.

2023-08-15 12:44 UTC, weichweich commented on docs/develop/02_chain/02_pallets/01_did.md
> +Freeing up memory reduces the deposit.
Memory is working memory, RAM while storage is persistent storage. Let's keep one wording here.

```suggestion
Freeing up storage reduces the deposit.
```

2023-08-15 13:38 UTC, Ad96el commented on docs/develop/02_chain/02_pallets/01_did.md
> +The base deposit is currently 2 KILT.
The base deposit is exactly [2 KILT](https://github.com/KILTprotocol/kilt-node/blob/develop/runtimes/common/src/constants.rs#L347) :thinking:

2023-08-15 13:45 UTC, weichweich commented on docs/develop/02_chain/02_pallets/01_did.md
> +The base deposit is currently 2 KILT.
Ah Sorry... it wasn't exactly 2 KILT before. Good to know. 😁

2023-08-15 14:39 UTC, weichweich approved these changes

2023-11-13 10:38 UTC, merged