Workshop overhaul: Final section
KILTprotocol/docs pull request #287
Opened 2023-11-18 14:43 UTC by ChrisChinchilla

## fixes KILTProtocol/ticket#2956
Overhaul to closing sections of workshop content included external contributions.

2023-11-21 10:10 UTC, Dudleyneedham requested changes
Minor comments again. Looks great

2023-11-21 10:10 UTC, Dudleyneedham commented on docs/develop/03_workshop/06_attestation.md
> +The credential is valid from the time an Attester attests it on chain until the time it is revoked.
With the VC changes in the future, this would need to change. Since you can add expiry dates to the credential. I think this should happen fairly soon. I would maybe put a ticket out there to ensure we change this to match.

2023-11-21 10:10 UTC, Dudleyneedham commented on docs/develop/03_workshop/06_attestation.md
> +In the `attestingFlow` function, the <span className="label-role claimer">Claimer</span> generates the demo credential and sends it to the <span className="label-role attester">Attester</span>.
```suggestion
In the `attesting Flow` function, the <span className="label-role claimer">Claimer</span> generates the demo credential and sends it to the <span className="label-role attester">Attester</span>.
```

2023-11-21 10:10 UTC, Dudleyneedham commented on docs/develop/03_workshop/06_attestation.md
> +In the `attestingFlow` function, the <span className="label-role claimer">Claimer</span> generates the demo credential and sends it to the <span className="label-role attester">Attester</span>.
Not sure if this was on purpose. If it was we can remove the suggestion.

2023-11-21 14:06 UTC, ChrisChinchilla commented on docs/develop/03_workshop/06_attestation.md
> +In the `attestingFlow` function, the <span className="label-role claimer">Claimer</span> generates the demo credential and sends it to the <span className="label-role attester">Attester</span>.
@Dudleyneedham Nope, this change was intentional, it's describing a function in the code

2023-11-23 14:08 UTC, Dudleyneedham approved these changes
LGTM

2023-11-23 15:26 UTC, merged