feat: adding code examples
KILTprotocol/docs pull request #5
Opened 2021-07-05 14:37 UTC by Dudleyneedham

## fixes https://github.com/KILTprotocol/ticket/issues/1438 &&  https://github.com/KILTprotocol/ticket/issues/1435 && https://github.com/KILTprotocol/ticket/issues/1436
Adding code examples

## How to test:

yarn install

yarn build

yarn start

## Checklist:

- [ ] I have verified that the code works
- [ ] I have verified that the code is easy to understand
  - [ ] If not, I have left a well-balanced amount of inline comments
- [ ] I have [left the code in a better state](https://deviq.com/principles/boy-scout-rule)
- [ ] I have documented the changes (where applicable)

2021-07-13 15:36 UTC, weichweich requested changes
The image needs to go into our folder.

2021-07-13 15:36 UTC, weichweich commented on docs/delegations.md
> +![https://i.imgur.com/UmSNC1m.png](https://i.imgur.com/UmSNC1m.png)
this should go into our resource folder at https://github.com/KILTprotocol/docs/tree/master/static/img

2021-07-13 15:36 UTC, weichweich commented on docs/delegations.md
> +Each CASE the delegator must call the revoke on the instantiated attestation object with the given delegator or parent of the delegator to revoke the attestation.
maybe we should tell the reader that this is an upper limit? So they can give more lookups and will get refunded the fees that they paid too much?

2021-07-13 15:36 UTC, weichweich commented on sidebars.js
> -    Features: ['mdx'],
do we want to disable `mdx`? had to look that up... https://mdxjs.com/ It looks uneccessary.

2021-07-16 09:19 UTC, Dudleyneedham commented on docs/delegations.md
> +![https://i.imgur.com/UmSNC1m.png](https://i.imgur.com/UmSNC1m.png)
Should I add this to the resource folder? Since I can see it in your PR already?

2021-07-16 09:21 UTC, Dudleyneedham commented on sidebars.js
> -    Features: ['mdx'],
Yes, sure. I will remove it.

2021-07-16 09:33 UTC, Dudleyneedham commented on docs/delegations.md
> +Each CASE the delegator must call the revoke on the instantiated attestation object with the given delegator or parent of the delegator to revoke the attestation.
I will add to the end of this. 
Each CASE the delegator must call the revoke on the instantiated attestation object with the given delegator or parent of the delegator to revoke the attestation. `The fee is taking considering the maximum number of lookups needed to reach all cases, these fees will be refunded if paid too much.`

2021-07-16 10:00 UTC, weichweich commented on sidebars.js
> -    Features: ['mdx'],
ah no i was completely confused by this. It doesn't enable features! I thought you disabled the mdx

2021-07-16 10:01 UTC, weichweich commented on docs/delegations.md
> +![https://i.imgur.com/UmSNC1m.png](https://i.imgur.com/UmSNC1m.png)
yeah already did it my self. 🙈 sorry

2021-07-16 10:02 UTC, weichweich commented on docs/delegations.md
> +Each CASE the delegator must call the revoke on the instantiated attestation object with the given delegator or parent of the delegator to revoke the attestation.
sounds good

2021-07-16 10:09 UTC, Dudleyneedham commented
Please re-review

2021-07-16 11:28 UTC, weichweich approved these changes
Nice

2021-07-16 11:29 UTC, merged