refactor: es modules & testable workshop
KILTprotocol/docs pull request #52
Opened 2022-02-16 14:26 UTC by weichweich

* switch from `require` to `import`
* make the workshop testable
  * execution will be more linear, less branching
  * 

## Checklist:

- [ ] I have verified that the code works
- [ ] I have verified that the code is easy to understand
  - [ ] If not, I have left a well-balanced amount of inline comments
- [ ] I have [left the code in a better state](https://deviq.com/principles/boy-scout-rule)
- [ ] I have documented the changes (where applicable)

2022-02-22 14:41 UTC, Dudleyneedham requested changes
Minor suggestions and comments

2022-02-22 14:41 UTC, Dudleyneedham commented on docs/sdk/1-workshop/03-attester/02-did.md
> +To create a DID we first initialize everything as we always do.
```suggestion
To create a DID we first initialize everything.
```

2022-02-22 14:41 UTC, Dudleyneedham commented on docs/sdk/1-workshop/03-attester/02-did.md
> +To create a DID we first initialize everything as we always do.
If you want to add something here, you should add a reason why we need to do this.

2022-02-22 14:41 UTC, Dudleyneedham commented on docs/sdk/1-workshop/04-claimer/01-did.md
> +Similar to the attester, the claimer too has to setup the DID keys.
```suggestion
Similar to the attester, the claimer must set up the DID keys.
```

2022-02-22 14:41 UTC, Dudleyneedham commented on docs/sdk/1-workshop/6-verification.md
> +A `Presentation` object is created by the <span class="label-role claimer">claimers</span> using a credential.
This doesn't makes sense. The claimer creates a credential from what?

2022-02-22 15:32 UTC, weichweich commented on docs/sdk/1-workshop/6-verification.md
> +A `Presentation` object is created by the <span class="label-role claimer">claimers</span> using a credential.
The presentation is derived from the credential. The user already has the credential?

2022-02-23 14:40 UTC, Dudleyneedham commented on docs/sdk/1-workshop/6-verification.md
> +A `Presentation` object is created by the <span class="label-role claimer">claimers</span> using a credential.
But that assumes the user knows what a presentation is and what they make it from. Being explicit is much better

2022-02-23 14:49 UTC, Dudleyneedham commented on docs/sdk/1-workshop/6-verification.md
> +A `Presentation` object is created by the <span class="label-role claimer">claimers</span> using a credential.
```suggestion
A credential creates the `Presentation` object by the <span class="label-role claimer">claimers</span>.
```

2022-02-23 14:49 UTC, Dudleyneedham commented on docs/sdk/1-workshop/6-verification.md
> +A `Presentation` object is created by the <span class="label-role claimer">claimers</span> using a credential.
The concept is fine, but I mean the way it reads.

2022-02-23 14:49 UTC, Dudleyneedham commented on docs/sdk/1-workshop/6-verification.md
> +A `Presentation` object is created by the <span class="label-role claimer">claimer</span> using a credential.
```suggestion
A credential is used to create the `Presentation` object by the <span class="label-role claimer">claimer</span>.
```

2022-02-23 14:52 UTC, Dudleyneedham approved these changes
LGTM

2022-02-28 09:25 UTC, merged