Update documentation
KILTprotocol/docs pull request #8
Opened 2021-07-20 15:31 UTC by weichweich

# fixes KILTprotocol/ticket/issues/1471

* black text for features on start page
* improve collator guide
* remove devnet from about KILT page
* fix overview svg

2021-07-23 13:06 UTC, weichweich commented
@Dudleyneedham I used a few docusaurus features and added a few more explanations to the collator guide

2021-07-26 08:50 UTC, Dudleyneedham requested changes
Some minor changes

2021-07-26 08:50 UTC, Dudleyneedham commented on docs/about-kilt.md
> +
```suggestion
```

2021-07-26 08:50 UTC, Dudleyneedham commented on docs/about-kilt.md
> +
```suggestion
```

2021-07-26 08:50 UTC, Dudleyneedham commented on docs/chain/collator.md
> +0. check that your node is fully synced with the relaychain & parachain. (best and finilazed block number is equal to the one shown in the polkadot apps & on subscan)
```suggestion
0. Check that your node is fully synced with the relaychain & parachain. (best and finalised block number is equal to the one shown in the polkadot apps & on subscan)
```

2021-07-26 08:50 UTC, Dudleyneedham commented on docs/chain/collator.md
> +2. the parachainStaking pallet will register your address in the session pallet. Check that your address is listed in `session > validators`
```suggestion
2. The parachainStaking pallet will register your address in the session pallet. Check that your address is listed in `session > validators`
```

2021-07-26 08:50 UTC, Dudleyneedham commented on docs/chain/collator.md
> +6. Check in the Polkadot Apps under `network > explorer` that your accountId is shown next to a block. You can be 100% sure that you produce blocks if you are listed there. If steps 1-5 all look fine
```suggestion
6. Check in the Polkadot Apps under `network > explorer` that your accountId is shown next to a block. You can be 100% sure that you produce blocks if you are listed there. If steps 1-5 all look fine for your collator but you don't see your blocks, you might not produce and send blocks fast enough. This can be caused by slow hardware or a slow internet connection. Also, note that a high bandwidth connection can still be slow if it has a high ping! Bandwidth != latency
```

2021-07-28 12:03 UTC, Dudleyneedham approved these changes
LGTM

2021-07-28 12:03 UTC, merged