feat: tested code examples
KILTprotocol/docs pull request #9
Opened 2021-07-21 15:06 UTC by weichweich

* load code examples from example directory
* execute all examples
* connect to peregrine and use peregrine in the workshop
* add github pipeline

2021-07-23 12:56 UTC, weichweich commented
@Dudleyneedham maybe we could do the same for the other code examples?

2021-08-11 13:09 UTC, Dudleyneedham requested changes
Looks good overall just need some minor suggestions

2021-08-11 13:09 UTC, Dudleyneedham commented on docs/chain/collator.md
> +With these parameters you can make RPCalls directly using curl.
`RPCalls` is a better name

2021-08-11 13:09 UTC, Dudleyneedham commented on docs/sdk/0-workshop/00-welcome.md
> +📦 Topics: <a href="https://github.com/KILTprotocol/sdk-js">KILT SDK</a> essentials, basic credential workflow without privacy enhancement. This includes creating a CTYPE and a claim; attesting a clai
Do we need the privacy enhancement in this sentence?

2021-08-11 13:09 UTC, Dudleyneedham commented on docs/sdk/0-workshop/03-identity.md
> +- A signing keypair, used to sign claims;
Do you need to inform them that it is used to sign claims? Maybe just say the following.

used to sign transactions such as claims.

2021-08-11 13:09 UTC, Dudleyneedham commented on docs/sdk/0-workshop/03-identity.md
> +In cryptography, a mnemonic is a random series of words. For example, `gold upset segment cake universe` is a mnemonic. It's used to generate keypairs. What's great about a mnemonic is that it's **hu
```suggestion
In cryptography, a mnemonic usually consists of 12 or 24 random series of words. For example, `gold upset segment cake universe` is a mnemonic. It's used to generate keypairs. What's great about a mnemonic is that it's **human-readable**. A person can memorize it, and use it later to re-generate their keypairs and address.
```

2021-08-11 13:31 UTC, Dudleyneedham approved these changes
LGTM

2021-08-11 13:31 UTC, merged