feat: add how-to-integrate page with link to distillery + placeholder for cookbook
KILTprotocol/docs pull request #97
Opened 2022-05-23 09:24 UTC by trusch

## fixes KILTProtocol/ticket#2009

add how-to-integrate page with link to distillery + placeholder for cookbook

## How to test:
Please provide a brief step-by-step instruction.
If necessary provide information about dependencies (specific configuration, branches, database dumps, etc.)

- Step 1
- Step 2
- etc.

## Checklist:

- [ ] I have verified that the code works
- [ ] I have verified that the code is easy to understand
  - [ ] If not, I have left a well-balanced amount of inline comments
- [ ] I have [left the code in a better state](https://deviq.com/principles/boy-scout-rule)
- [ ] I have documented the changes (where applicable)

2022-05-23 13:43 UTC, tjwelde requested changes
The docs can't be built anymore:
```
ERROR] Error: Docusaurus found broken links!
                                    Please check the pages of your site in the list below, and make sure you don't reference any path that does not exist.
                                    Note: it's possible to ignore broken links with the 'onBrokenLinks' Docusaurus configuration, and let the build pass.
                                    Exhaustive list of all broken links found:
                                    - On source page path = /docs/develop/workshop/overview:
                                    -> linking to ../1-sdk/9-core-feature/0_did.md#light-dids (resolved as: /docs/develop/1-sdk/9-core-feature/0_did.md)
                                    ```

2022-05-23 13:43 UTC, tjwelde commented on docs/develop/1-sdk/03-how-to-integrate.md
> +# Usage in nodejs
I think these items should be separate Documents tied together with a sidebar

2022-05-25 15:38 UTC, wischli commented on docs/develop/1-sdk/03-how-to-integrate.md
> +# Usage in nodejs
Also, from a SEO perspective, main headlines shouldn't be H1 (e.g. `#`) because that's reserved for the title. Sub headlines should start as H2 (e.g. `##`).

2022-06-01 08:49 UTC, trusch commented
superseeded by #110

2022-06-01 08:49 UTC, closed without merging